apiVersion: v2
name: media-shared
description: Shared resources for media server (namespace, storage)
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - media
  - storage
maintainers:
  - name: dave6892
