---
# PersistentVolume for Plex media
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/snap/microk8s/common/default-storage/plex-media
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath

---
# PersistentVolume for Plex config
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /var/snap/microk8s/common/default-storage/plex-config
    type: DirectoryOrCreate
