apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    {{- toYaml .Values.storage.config.accessModes | nindent 4 }}
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}
